#
# GitHub Pages / Jekyll Configuration for Backtest Brewery
#

# Site Identity
name: Backtest Brewery
title: Backtest Brewery
description: Quantitative Musings on Trading, Strategies, and Markets
avatar: /images/avatar.png   # optional — place avatar.png inside /images folder

# Author / Footer Links
footer-links:
  github: backtestbrewery
  linkedin: backtestbrewery
  twitter: backtestbrewery
  email: backtestbrewery@gmail.com
  rss: backtestbrewery

# Commenting & Analytics
disqus: backtestbrewery
comments: true
google_analytics: UA-XXXXXXXXX-X   # replace with your GA ID if available

# Site URLs
url: https://backtestbrewery.github.io   # User site URL
baseurl: ""                              # keep empty for user/org sites

# Markdown & Formatting
markdown: kramdown
highlighter: rouge
permalink: /:title/

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Version
version: v1.0.0

# Sass
sass:
  sass_dir: _scss
  style: :expanded

# Plugins (modern syntax)
plugins:
  - jemoji
  - jekyll-sitemap

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
