name: Tr8dr
description: Musings on Algorithms, Models, and the Markets

# Add this line
theme: jekyll-theme-minimal

avatar: 

footer-links:
  email: jonathan.shore@gmail.com
  github: tr8dr
  linkedin: shorej
  rss: # leave empty
  twitter: tr8dr

disqus: tr8dr
comments: true
google_analytics: UA-2891999-5

# For organization/project site
url: https://backtestbrewery.github.io/
baseurl: ""  # empty for organization sites

# Keep the rest of your config the same...
markdown: kramdown
highlighter: rouge
# ... etc
